name: Deploy Python Lambda v2

on:
  push:
    branches:
      - main
    # paths:
      # - '**.py' # Change to the file extension of the language that you are using.

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      -  name: Creating deployment zip
         run: | 
          # Constants
          S3_BUCKET=hello-lambda-src
          S3_KEY=lambda_function.zip
          LAMBDA_FUNCTION_NAME=arn:aws:lambda:us-east-1:972194656918:function:hello 
          ZIP_NAME=updated_lambda.zip
          DEPLOY_DIR=deployment_zip

          sudo apt install zip
          mkdir -p ./$DEPLOY_DIR 
          # install python deps (later)
          # pip install snowflake-connector-python --platform manylinux2010_x86_64 --only-binary=:all: -t ./$DEPLOY_DIR
          
          # single py...will need updating
          cp ./lambda_function.py  ./$DEPLOY_DIR
          cd $DEPLOY_DIR 
          zip -r $ZIP_NAME *

          # Upload the updated zip to S3
          aws s3 cp $ZIP_NAME s3://$S3_BUCKET/$S3_KEY
          aws s3 cp updated_lambda.zip s3://$S3_BUCKET/$S3_KEY

          # Update Lambda
          aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --s3-bucket $S3_BUCKET --s3-key $S3_KEY
        